@startuml
skinparam defaultFontName Courier
skinparam shadowing false
skinparam noteBackgroundColor #eee
skinparam noteBorderColor transparent
skinparam sequenceGroupBorderColor #ccc
skinparam sequenceReferenceBorderColor #ccc

title model-task 模型分析任务调度时序图

actor       "video-decoder"     as VD
participant "model-task"        as MT
participant "atomic-model"      as AM


|||
==分发 图片消费通知 API==

VD -> MT: NotifyPictureAnalyze

ref over MT
POST https://${model-task_host}/notify

入参:图片URI,摄像头ID,场景...
end ref

|||
MT -> AM: 以工作流调用对应的场景分析服务



@enduml